export const APP_NAME = 'SchemeIndia AI'
export const APP_TAGLINE = 'Every benefit you deserve. Finally in one place.'

export const ROUTES = {
  landing: '/',
  signin: '/signin',
  signup: '/signup',
  search: '/search',
  categories: '/categories',
  categoryDetail: '/category/:slug',
  about: '/about',
  onboarding: '/onboarding',
  dashboard: '/dashboard',
  disha: '/disha',
  schemes: '/schemes',
  mySchemes: '/my-schemes',
  states: '/states',
  stateDetail: '/states/:stateSlug',
  stateAlias: '/state/:stateSlug',
  wellness: '/wellness',
  rooms: '/rooms',
  journal: '/journal',
  documents: '/documents',
  profile: '/profile',
  offline: '/offline',
} as const

export const CRISIS_SUPPORT =
  'If you\'re going through something serious, iCall (9152987821) and Vandrevala Foundation (1860-2662-345) are free, confidential, and available 24/7.'

export const IN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
] as const
